version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - RUST_BACKTRACE=1
    # Overrides default command so things don't shut down after the process ends.
    network_mode: host